before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: kwobmSYft53xq4GFYzPXWUbTeAeKz4Gi5TDBQYklRufeh4stKftf8BI7AdiMelmabR6Z+XwRsBybr7rZzfTlK3GGIh4qd+v6rJRQgPwpr65ygF+b/IfwVNRBkAoYG3SUcnL7f6ckbB15zlOCKojc8kCndkhIJPy8VWa5HabPhmdkAM0wUST9nnNK/rxyqVuChA5wasxF0W63YlE23rzgOJ+zYjpPQqnzG2bFugGgCwugTrt/jGO7jl9YoQIJXoMQg+5fAGKxyST1fA4j4iYlE/iRnJ0hKam4Qo+uq4p7anvSukqvPvVyuf4XBzq8d6vsqd+MRalGcgEmjzHb+fKzTuRCnVX4G603TSnf+m5YvulUM1+G/8irq3JuVYyZLLVGZU5P0btJIhWU9p1IxqAirs6aUFqR535cvkxdNKDKqwzyi0Bx3fk2RUOMQ4UzW4NsXD1TxeTj17rtsKcmPYG1IpuCqmAmnJye6n1B7N78CuUIoho8E+dOsJw8klmyAviYS8IK3K6OSSeDF+PcP5YwVapCxLHQdRCxTKbNc8lHZpJw4HopZpOVXbmjeEOnt1pCu+CKeUuK99CciZo0rLhUabvmjVlpKYe23dloTWEsbWLwgRCdJlXLcbnAb5p56Pq0Lcq6oLv2RPB6yrBBo4nGRR+5hzIvxNv3BlukuA6Wd48= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
